micronaut:
  application:
    name: micronaut-server
  server:
    port: ${PORT}
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/redoc
        mapping: /redoc/**
custom:
  example: value
  server:
    base-path: /api
    secret: ${SECRET}
  integrations:
    placeholder:
      url: ${PLACEHOLDER_API_URL}
